language: go

go: 
 - 1.x

matrix:
  include:
    - os: linux
      before_install:
        - sudo add-apt-repository ppa:webkit-team/ppa -y
        - sudo apt-get update
        - sudo apt-get install libwebkit2gtk-4.0-dev -y
      env: WEBVIEW=gtk
    - os: osx
      osx_image: xcode8.3
      env: WEBVIEW=cocoa

script:
  - make example
